/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Eduardo
 */
public class InterfazPedido extends javax.swing.JPanel {

    /**
     * Creates new form InterfazPedido
     */
    public InterfazPedido() {
        initComponents();
        DcDia.setEnabled(false);
        DcInicio.setEnabled(false);
        DcFinal.setEnabled(false);
        McMes.setEnabled(false);
    }
     
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JlTipoPedido = new javax.swing.JLabel();
        CbTipoPedido = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        DcDia = new com.toedter.calendar.JDateChooser();
        McMes = new com.toedter.calendar.JMonthChooser();
        DcInicio = new com.toedter.calendar.JDateChooser();
        DcFinal = new com.toedter.calendar.JDateChooser();
        JlInicio = new javax.swing.JLabel();
        JlFinal = new javax.swing.JLabel();
        JbAceptar = new javax.swing.JButton();
        JbSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        JlDia = new javax.swing.JLabel();
        JlDia1 = new javax.swing.JLabel();
        JlDia2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pharma System: Generar Pedido.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 11), new java.awt.Color(255, 102, 0))); // NOI18N
        setPreferredSize(new java.awt.Dimension(722, 535));
        setLayout(null);

        JlLogo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        JlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logosalud.jpg"))); // NOI18N
        JlLogo.setText("                   Pedidos");
        JlLogo.setMaximumSize(new java.awt.Dimension(587, 80));
        JlLogo.setMinimumSize(new java.awt.Dimension(587, 80));
        JlLogo.setPreferredSize(new java.awt.Dimension(587, 80));
        add(JlLogo);
        JlLogo.setBounds(10, 20, 710, 80);

        jPanel1.setBackground(new java.awt.Color(122, 122, 122));

        JlTipoPedido.setBackground(new java.awt.Color(255, 255, 255));
        JlTipoPedido.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JlTipoPedido.setForeground(new java.awt.Color(255, 255, 255));
        JlTipoPedido.setText("Tipo de pedido:");

        CbTipoPedido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion.", "Diario.", "Semanal.", "Mensual." }));
        CbTipoPedido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbTipoPedidoItemStateChanged(evt);
            }
        });
        CbTipoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTipoPedidoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Clave", "Medicamento", "Cantidad Prescrita", "Cantidad Disponible"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        JlInicio.setBackground(new java.awt.Color(255, 255, 255));
        JlInicio.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JlInicio.setForeground(new java.awt.Color(255, 255, 255));
        JlInicio.setText("De:");

        JlFinal.setBackground(new java.awt.Color(255, 255, 255));
        JlFinal.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JlFinal.setForeground(new java.awt.Color(255, 255, 255));
        JlFinal.setText("a:");

        JbAceptar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        JbAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.png"))); // NOI18N
        JbAceptar.setText("Aceptar");
        JbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAceptarActionPerformed(evt);
            }
        });

        JbSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        JbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        JbSalir.setText("Salir");

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JlDia.setBackground(new java.awt.Color(255, 255, 255));
        JlDia.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JlDia.setForeground(new java.awt.Color(255, 255, 255));
        JlDia.setText("Seleccione un dia:");

        JlDia1.setBackground(new java.awt.Color(255, 255, 255));
        JlDia1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JlDia1.setForeground(new java.awt.Color(255, 255, 255));
        JlDia1.setText("Seleccione el mes:");

        JlDia2.setBackground(new java.awt.Color(255, 255, 255));
        JlDia2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        JlDia2.setForeground(new java.awt.Color(255, 255, 255));
        JlDia2.setText("Seleccione el dia inicial y final del pedido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JbSalir)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JlTipoPedido)
                                .addComponent(CbTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(JlDia2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(JlInicio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(JlFinal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(64, 64, 64)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlDia1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(McMes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JlDia)
                                        .addComponent(DcDia, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(1, 1, 1)))
                            .addGap(31, 31, 31)
                            .addComponent(JbAceptar))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JlTipoPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbTipoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JlDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DcDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlDia2)
                            .addComponent(JlDia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JlFinal)
                            .addComponent(DcFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(McMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JlInicio)
                    .addComponent(DcInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JbAceptar))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbSalir)
                    .addComponent(jButton1))
                .addGap(41, 41, 41))
        );

        add(jPanel1);
        jPanel1.setBounds(10, 100, 700, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void CbTipoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTipoPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbTipoPedidoActionPerformed

    private void JbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JbAceptarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CbTipoPedidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbTipoPedidoItemStateChanged
         int seleccionado=CbTipoPedido.getSelectedIndex();
         String FechaPedido=(String)CbTipoPedido.getItemAt(seleccionado);
        

        if(FechaPedido.equalsIgnoreCase("Diario.")){
            DcDia.setEnabled(true);
            DcInicio.setEnabled(false);
            DcFinal.setEnabled(false);
            McMes.setEnabled(false);
        }
        if(FechaPedido.equalsIgnoreCase("Semanal.")){
            DcInicio.setEnabled(true);
            DcDia.setEnabled(false);
            McMes.setEnabled(false);
            
        }
        if(FechaPedido.equalsIgnoreCase("Semanal.")){
            DcFinal.setEnabled(true);
            DcDia.setEnabled(false);
            McMes.setEnabled(false);
        }
        if(FechaPedido.equalsIgnoreCase("Mensual.")){
            McMes.setEnabled(true);
            DcDia.setEnabled(false);
            DcInicio.setEnabled(false);
            DcFinal.setEnabled(false);
            
        }
    }//GEN-LAST:event_CbTipoPedidoItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbTipoPedido;
    private com.toedter.calendar.JDateChooser DcDia;
    private com.toedter.calendar.JDateChooser DcFinal;
    private com.toedter.calendar.JDateChooser DcInicio;
    private javax.swing.JButton JbAceptar;
    private javax.swing.JButton JbSalir;
    private javax.swing.JLabel JlDia;
    private javax.swing.JLabel JlDia1;
    private javax.swing.JLabel JlDia2;
    private javax.swing.JLabel JlFinal;
    private javax.swing.JLabel JlInicio;
    private javax.swing.JLabel JlLogo;
    private javax.swing.JLabel JlTipoPedido;
    private com.toedter.calendar.JMonthChooser McMes;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
